# Generated by Django 5.0.4 on 2024-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='receta',
            field=models.TextField(default='Sin receta'),
            preserve_default=False,
        ),
    ]
